# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-26 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20180226_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
