# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-26 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20180226_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '\u7528\u6237\u7559\u8a00\u4fe1\u606f', 'verbose_name_plural': '\u7528\u6237\u7559\u8a00\u4fe1\u606f'},
        ),
    ]
